# shellcheck disable=SC3000-SC4000
MARIADB_EXPECTED_BUFFER_POOL_MB=""

mariadb_check_value() {
  local label expected actual query

  label="$1"
  expected="$2"
  query="$3"

  if ! actual="$(mariadb -uroot -NBe "$query" 2>/dev/null)"; then
    echo -e "Ошибка проверки MariaDB: ${RED}${label}${WHITE}"
    return 1
  fi

  if [[ "$actual" != "$expected" ]]; then
    echo -e "Ошибка проверки MariaDB: ${label}: ожидалось ${GREEN}${expected}${WHITE}, получено ${RED}${actual}${WHITE}"
    return 1
  fi
}

mariadb_verify_installation() {
  local expected_buffer_pool_mb="${1:-}"

  mariadb_check_value "anonymous users удалены" "0" "SELECT COUNT(*) FROM mysql.user WHERE User='';" || return 1
  mariadb_check_value "test database удалена" "0" "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='test';" || return 1
  mariadb_check_value "root доступен только локально" "0" "SELECT COUNT(*) FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');" || return 1
  mariadb_check_value "server charset" "utf8mb4" "SELECT @@character_set_server;" || return 1
  mariadb_check_value "server collation" "utf8mb4_unicode_ci" "SELECT @@collation_server;" || return 1
  if [[ -n "$expected_buffer_pool_mb" ]]; then
    mariadb_check_value "InnoDB buffer pool, MB" "$expected_buffer_pool_mb" "SELECT FLOOR(@@innodb_buffer_pool_size / 1048576);" || return 1
  fi

  Up
  echo -e "Проверки MariaDB: ${GREEN}OK${WHITE}"
  Down
}

mariadb_recommended_buffer_pool_size() {
  local memory_kb memory_mb buffer_pool_mb

  memory_kb="$(awk '/^MemTotal:/ { print $2; exit }' /proc/meminfo)"
  if [[ ! "$memory_kb" =~ ^[0-9]+$ ]]; then
    echo "128M"
    return
  fi

  memory_mb=$((memory_kb / 1024))

  if (( memory_mb <= 1024 )); then
    echo "128M"
  elif (( memory_mb <= 2048 )); then
    echo "256M"
  elif (( memory_mb <= 4096 )); then
    echo "768M"
  elif (( memory_mb <= 8192 )); then
    echo "1G"
  elif (( memory_mb <= 16384 )); then
    echo "2G"
  else
    buffer_pool_mb=$((memory_mb * 20 / 100))
    buffer_pool_mb=$((buffer_pool_mb / 128 * 128))
    (( buffer_pool_mb > 8192 )) && buffer_pool_mb=8192
    echo "${buffer_pool_mb}M"
  fi
}

mariadb_configure_buffer_pool() {
  local config_file="/etc/my.cnf.d/rish-performance.cnf"
  local buffer_pool_size

  if [[ -e "$config_file" ]]; then
    echo -e "Конфигурация MariaDB ${YELLOW}${config_file}${WHITE} уже существует и не будет изменена."
    return
  fi

  buffer_pool_size="$(mariadb_recommended_buffer_pool_size)"
  case "$buffer_pool_size" in
    *G)
      MARIADB_EXPECTED_BUFFER_POOL_MB=$((${buffer_pool_size%G} * 1024))
      ;;
    *M)
      MARIADB_EXPECTED_BUFFER_POOL_MB="${buffer_pool_size%M}"
      ;;
  esac

  cat >"$config_file" <<EOF
# Generated by RISH during the initial MariaDB installation.
[mysqld]
innodb_buffer_pool_size=${buffer_pool_size}
EOF
  chmod 644 "$config_file"

  echo -e "Размер InnoDB buffer pool для этого сервера: ${GREEN}${buffer_pool_size}${WHITE}."
  if [[ -n "${LOG_FILE:-}" ]]; then
    echo "MariaDB innodb_buffer_pool_size=${buffer_pool_size}" >>"$LOG_FILE"
  fi
}

mariadb_install() {

  Install MariaDB-server MariaDB-client
  systemctl start mariadb
  systemctl enable mariadb

  Up
  echo -e "Производим настройку безопасности ${GREEN}mysql_secure_installation${WHITE}"
  Down
  sed -i '/character-set-server=/d' /etc/my.cnf.d/server.cnf
  sed -i '/collation-server=/d' /etc/my.cnf.d/server.cnf
  sed -i "s/^\[mysqld\]/\[mysqld\]\ncharacter-set-server=utf8mb4\ncollation-server=utf8mb4_unicode_ci/" /etc/my.cnf.d/server.cnf

  mariadb-secure-installation <<EOF

n
n
y
y
y
y

EOF
  # mysql -uroot  -e "ALTER USER root@localhost IDENTIFIED VIA mysql_native_password USING PASSWORD(\"${pass}\");"
  sed -i "s/^#bind-address.*$/bind-address=127.0.0.1/" /etc/my.cnf.d/server.cnf
  mariadb_configure_buffer_pool
  systemctl restart mariadb
  mariadb_verify_installation "$MARIADB_EXPECTED_BUFFER_POOL_MB"
}
